mysite/blog/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', views.category_setting, name='category_setting'),
    path('ca_del<int:pk>', views.category_delete, name='category_delete'),
    path('ca<int:num>', views.post_list, name='post_list'),
    path('ca<int:number>/p<int:pk>', views.post_detail, name='post_detail'),
    path('ca<int:number>/new', views.post_new, name='post_new'),
    path('ca<int:number>/p<int:pk>/edit', views.post_edit, name='post_edit'),
    path('ca<int:number>/p<int:pk>/delete', views.post_delete, name='post_delete'),
    path('ca<int:number>/p<int:post_pk>/comment_del<int:comment_pk>', views.comment_delete, name='comment_delete'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
]

mysite/blog/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    number = models.IntegerField()
    title = models.CharField(max_length=200)
    text = models.TextField()
    img = models.ImageField(blank=True, upload_to='%Y/%m/%d/img')
    file = models.FileField(blank=True, upload_to='%Y/%m/%d/file')
    #file = models.FileField(blank=True, upload_to='%Y/%m/%d/file')

    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

class Comment(models.Model):
    num = models.IntegerField()
    name = models.CharField(max_length=50)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    def publish(self):
        self.save()

    def __str__(self):
        return self.text

class Category(models.Model):
    name = models.CharField(max_length=50)
    number = models.IntegerField(primary_key=True)
    def publish(self, num):
        number = num
        self.save()

    def __str__(self):
        return self.name

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from .models import Category
from .models import Comment
from django.utils import timezone
from .form import PostForm, CommentForm, CategoryForm
from django.shortcuts import redirect
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf.global_settings import TEMPLATES
import math

#TEMPLATES[0]['OPTIONS']['context_processors'].insert(0, 'django.core.context_processors.request')

# Create your views here.
 
def category_setting(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            category = form.save(commit=False)
            category.save()
            return redirect(category_setting)
    else:    
        form = CategoryForm()
    return render(request, 'blog/main_page.html', {'form': form})


def post_list(request, num=1):
    posts_per_page = 7

    text = request.GET.get('text', '')
    target = request.GET.get('target', '')

    list = Post.objects.filter(number = num).order_by('-created_date') # 카테고리 별로 불러오기
    if target == "title":
        list = list.filter(title__icontains = text)
    elif target == "contents":
        list = list.filter(text__icontains = text)
    

    page = request.GET.get('page',1)
    cur_max = int((int(page)-1) / 5) * 5 + 5;
    cur_min = int((int(page)-1) / 5) * 5 + 1;
    paginator = Paginator(list, posts_per_page)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    max_len = math.ceil(len(list)/posts_per_page)
    return render(request, 'blog/post_list.html', {'posts' : posts, 'num':num, 'max_len': max_len, 'cur_max':cur_max,'cur_min':cur_min, 'text':text,'target':target})


def post_detail(request, number, pk): #  포스트 출력 및 댓글입력
    post = get_object_or_404(Post, pk=pk)
    comment = Comment.objects.filter(num = pk).order_by('created_date')

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.created_date = timezone.now()
            comment.num = pk
            comment.save()
            return redirect(post_detail, number=number, pk=pk)
    else:    
        form = CommentForm()

    return render(request, 'blog/post_detail.html', {'post': post, 'num' : number, "comments":comment, 'form':form, })


def post_new(request, number):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES) # 뒤에 request.FILES 안적으면 파일 안올라감
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.created_date = timezone.now()
            post.number = number
            post.save()
            return redirect(post_detail, number=number, pk=post.pk)
    else:    
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})


def comment_new(request, number, pk): # 댓글 달기
    if request.method == "POST":
        form = CommentForm(request.POST) # 뒤에 request.FILES 안적으면 파일 안올라감
        if form.is_valid():
            comment = form.save(commit=False)
            comment.created_date = timezone.now()
            comment.num = pk
            comment.save()
            return redirect(post_detail, number=number, pk=pk)
    else:    
        form = CommentForm()
    return render(request, 'blog/post_detail.html', {'form': form})

def post_edit(request, number, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect(post_detail, number = number, pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

def post_delete(request, number, pk):
    post = Post.objects.get(pk = pk)
    post.delete()
    return redirect(post_list, num=number)

def category_delete(request,pk):
    category = Category.objects.get(pk = pk)
    category.delete()
    return redirect(category_setting)

def comment_delete(request, number, post_pk, comment_pk):
    comment = Comment.objects.get(pk = comment_pk)
    comment.delete()
    return redirect(post_detail, number=number, pk=post_pk)

def category_list(request):
    categorys = Category.objects.order_by('pk')
    return render(request, 'blog/base.html', {'categorys': categorys})

mysite/blog/templates/blog/base.html
{% load static %}
<html>
    <head>
        <title>블로그</title>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}?ver=26">
        <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <!-- 부트스트랩 CDN -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css">
        <!-- 폰트어썸 CDN -->
        <link rel=”stylesheet” href=”http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css“>
    </head>

    <style type="text/css">
        a:link { color: black; text-decoration: none; font-family: Oswald;}
        a:visited { color: black; text-decoration: none;}
    </style>
    
    <body class="wrap">
        <div style="margin-left: 15%; width: 70%;">
            <div class ="site-header">   
                <h1><br><a href="/">  <span> teal's blog </span></a></h1> 
            </div>
            <div id ="category" class = "category navbar navbar-default"> 
                    <span style="font-size: 35px; font-weight:700;">카테고리</span><br>
                    <div>
                        
                        {% for category in categor %}
                            {% if category.number != num %}
                            <div id="category-list">
                                <span id="category-element"><a href="{% url 'post_list' num=category.number %}">{{ category.name }}</a></span><br>
                            </div>
                            {% elif category.number == num %}
                            <div id="category-select">
                                    <span id="category-element"><a href="{% url 'post_list' num=category.number %}">{{ category.name }}</a></span><br>
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                        <span id ="category-button">∧</span>

            </div>
            <div id ="main-space" ">
                {% block content %}
                {% endblock %}
            </div>

        </div>
        <footer  id = "footer-text">
            <div style="font-size:30px;">
                <a href="https://github.com/teal94"><span class="fab fa-github-square"></span></a>&nbsp;&nbsp;
                <a href="https://www.facebook.com/profile.php?id=100008022575058"><span class="fab fa-facebook-square"></span></a>&nbsp;&nbsp;
                <a href="mailto:abdh94@naver.com"><span class="fas fa-envelope-square"></span></a>&nbsp;&nbsp;&nbsp
                <span style="font-size:20px;" class="far fa-copyright">&nbspteal</span>
            </div>
            </footer>
        <script>
            $(document).ready(function(){
                $(".category>#category-button").click(function(){
                    var submenu =  $(this).prev("div");
                    // $(this).prev("div").toggleClass("hide");
                    if(submenu.is(":visible")){
                        submenu.slideUp();
                        $("#category-button").html("∨")
                    }else{
                        submenu.slideDown();
                        $("#category-button").html("∧")
                    }
                });
            });
        </script>

    </body>

</html>

mysite/blog/templates/blog/main_page.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="setting">
    <div id = "comment">
            <form method="POST" class="comment-form" action="" enctype="multipart/form-data" 
            style=" border-bottom : 1px solid #eeeeee; padding-bottom: 30px;padding-top: 20px">{% csrf_token %}
                {{ form.non_field_errors }}
                <div class="fieldWrapper">
                        {{ form.name.errors }}
                        <label for="id_title" style="font-size: 35px;">카테고리 제목</label><br>
                        {{ form.name }}
                </div><br>
                <div style="float: right;">
                        <button type="submit" class="save btn btn-primary"style="font-size: 25px">카테고리 작성</button>
                </div> 
            </form> 

            {% for category in categor %}
            <div style="border-bottom : 1px solid #eeeeee;">
                <span style="font-size: 35px">{{ category.name }}</span><br>
                <div style="float: right;">
                        <a href="{% url 'category_delete' pk=category.pk %}" class="save btn btn-primary button-text-color"><span>카테고리 삭제</span></a>
                </div><br><br><br>
            </div>
            {% endfor %}

    </div>
</div>
{% endblock %}

mysite/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        <div id ="main" >
            
            <span style="font-size: 35px"><a href="{% url 'post_detail' number=num pk=post.pk %}">{{ post.title }} </a></span>
            <br><span id="date" style="color:#aaaaaa;" >{{post.published_date|date:"Y-m-d"}} 작성</span><br><br>
            {% if post.img %}
                <img src = "{{ post.img.url }}"/>
            {% endif %}

            <p>{{ post.text|linebreaksbr }}</p>
            
            {% if post.file %}
            <br>
                <a href = "{{ post.file.url }}" download><span class="glyphicon glyphicon-download-alt" style="font-size: 20px"> {{post.file}}</span> </a>
            {% endif %}
        </div>

        <div style="float: right;margin-right: 10px">
                    
                <a class="btn btn-primary button-text-color" href="{% url 'post_delete' number=num pk=post.pk %}"><span>포스트 삭제</span></a>
        </div>
        <div style="float: right;margin-right: 10px">
                <a class="btn btn-primary button-text-color" href="{% url 'post_edit' number=num pk=post.pk %}"><span>포스트 수정</span></a>
        </div><br><br>
        
    </div>
    <div id = "comment">
            {% for comment in comments %}
            <div style="border-bottom : 1px solid #eeeeee;">
                <span style="font-size: 35px">{{ comment.name }}</span><br>
                <span style="font-size: 20px; word-break: break-all;">{{ comment.text }}</span><br>
                <span style="font-size: 15px">{{comment.created_date}} 작성</span>
                <div id="button"style="float: right;">
                        <a href="{% url 'comment_delete' number=num post_pk=comment.num comment_pk=comment.pk %}" class="btn btn-primary
                        button-text-color"><span>댓글 삭제</span></a>
                </div><br><br><br>
            </div>
            {% endfor %}
            <br>
            <form method="POST" class="comment-form" action="" enctype="multipart/form-data">{% csrf_token %}
                {{ form.non_field_errors }}
                
                <div class="comment-part">
                        {{ form.name.errors }}
                        <label for="id_title" style="font-size: 20px;">댓글 제목</label><br>
                        {{ form.name }}
                </div><br>
                <div class="comment-part">
                        {{ form.text.errors }}
                        <label for="id_title" style="font-size: 20px;">댓글 내용</label><br>
                        {{ form.text }}
                        <div style="float: right;">
                                <button type="submit" class="save btn btn-primary">댓글 작성</button>
                        </div>
                </div><br>
            </form>     
    </div>
{% endblock %}

mysite/blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}

    <div style="padding-left: 50px">
        <h1>New post</h1>
        <form method="POST" class="post-form" action="" enctype="multipart/form-data">{% csrf_token %}
            {{ form.non_field_errors }}
            
            <div class="fieldWrapper">
                    {{ form.title.errors }}
                    <label for="id_title" style="font-size: 20px;">제목</label><br>
                    {{ form.title }}
            </div><br>


            <div>
                    {{ form.text.errors }}
                        <label for="id_text" style="font-size: 20px;">내용</label><br>
                    {{ form.text }}
            </div><br>
            <div class="fieldWrapper" id = "print-img">
                    {{ form.img.errors }}
                    <label for="id_img" style="font-size: 20px;">이미지</label><br>
                    {{ form.img }}
            </div><br>
            <div class="fieldWrapper" id = "print-img">
                    {{ form.file.errors }}
                    <label for="id_file" style="font-size: 20px;">첨부파일</label><br>
                    {{ form.file }}
            </div>
            <div style="float: right;">
                <button type="submit" class="save btn btn-default">작성 완료</button>
            </div>
        </form>
    </div>
{% endblock %}

mysite/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    <div id ="main">
        <div id="post-list">
            {% for post in posts %}
                <span style="font-size: 35px"><a href="{% url 'post_detail' number=num pk=post.pk %}">{{ post.title }} </a></span>
                <span style="font-size: 15px; color:#aaaaaa;">{{post.published_date|date:"Y-m-d"}} 작성</span><br><br>
            {% endfor %}
        </div>

        {% if posts.has_other_pages %} 
            <ul class="pagination">
            {% if posts.has_previous %}
                <li><a href="?page={{ 1 }}&target={{target}}&text={{text}}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                <li><a href="?page={{ posts.previous_page_number }}&target={{target}}&text={{text}}"><span aria-hidden="true">&lsaquo;</span></a></li>
            {% else %}
                <li><a href="#"aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                <li><a href="#"aria-label="Previous"><span aria-hidden="true">&lsaquo;</span></a></li>
            {% endif %}
            {% for i in posts.paginator.page_range %}
                {% if cur_max >= i and cur_min <= i %}
                    {% if posts.number == i %}
                        <li><a href="#" style="background-color: #eeeeee;">{{ i }}</a></li>
                    {% else %}
                        <li><a href="?page={{ i }}&target={{target}}&text={{text}}">{{ i }}</a></li>
                    {% endif %}
                {% endif %}
            {% endfor %}

            {% if posts.has_next %}
                <li><a href="?page={{ posts.next_page_number }}&target={{target}}&text={{text}}" aria-label="Next"><span aria-hidden="true">&rsaquo;</span></a></li>
                <li><a href="?page={{ max_len }}&target={{target}}&text={{text}}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
            {% else %}
                <li><a href="#" aria-label="Next"><span>&rsaquo;</span></a></li>
                <li><a href="#" aria-label="Next"><span>&raquo;</span></a></li>
            {% endif %}
        {% endif %}

        </ul><br>
        <div style="float: right;font-size:25;">
                <a class="save btn btn-primary button-text-color" href="{% url 'post_new' number=num %}"><span>포스트 작성</span></a>
        </div>

        <form action="" method="GET">{% csrf_token %}
                <select name = "target" style="float: left; height: 33px; margin-right: 10px">
                        <option value="title">제목</option>
                        <option value="contents">내용</option>
                    </select>
                <input type="text" name="text" class="form-control" value="{{ text }}" style="width: 50%; float: left;margin-right: 10px">
                <input type="submit" class="save btn btn-default" value="검색">
        </form>
    </div>
{% endblock %}